services:
  postgres:
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD_SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  app:
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
    environment:
      DB_HOST=${DB_HOST}
      DB_PORT=${DB_PORT}
      DB_NAME=${DB_NAME}
      DB_USER=${DB_USER
      DB_PASSWORD=${DB_PASSWORD}
      IMAP_SERVER=${IMAP_SERVER}
      IMAP_USER=${IMAP_USER}
      IMAP_PASSWORD=${IMAP_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy
    volumes: ./src:/app/src